// <auto-generated />
using Mahas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mahas.Data.Migrations.MahasiswaDBMigration
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250708022659_add table matakuliah dan nilai")]
    partial class addtablematakuliahdannilai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mahas.Data.Dao.JurusanDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Kode")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JurusanDao");
                });

            modelBuilder.Entity("Mahas.Data.Dao.MahasiswaDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("IPK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("JurusanId")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nim")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JurusanId");

                    b.ToTable("Mahasiswas");
                });

            modelBuilder.Entity("Mahas.Data.Dao.MahasiswaDao", b =>
                {
                    b.HasOne("Mahas.Data.Dao.JurusanDao", "Jurusan")
                        .WithMany()
                        .HasForeignKey("JurusanId");

                    b.Navigation("Jurusan");
                });
#pragma warning restore 612, 618
        }
    }
}
